receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319
  mysql:
    endpoint: db:3306
    username: root
    password: mysql
    tls:
      insecure: true
    collection_interval: 30s
    initial_delay: 30s
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
  fluentforward:
    endpoint: 0.0.0.0:8006
  filelog/app:
    include: ["/app/log/*.log"]
    start_at: end
    operators:
      - type: json_parser
        on_error: send
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        severity:
          parse_from: attributes.severity

processors:
  batch:
    timeout: 5s
    send_batch_size: 5000
    send_batch_max_size: 5000
  batch/1m:
    timeout: 1m
  resource/namespace:
    attributes:
      - key: service.namespace
        value: apm-demo
        action: upsert
  resource/namespace_with_servicename:
    attributes:
      - key: service.name
        value: sample-app
        action: insert
      - key: service.namespace
        value: apm-demo
        action: upsert
  transform/applog:
    log_statements:
      - context: log
        statements:
          - set(time_unix_nano, observed_time_unix_nano) where time_unix_nano == 0
          - set(trace_id.string, attributes["trace_id"]) where attributes["trace_id"] != nil
          - delete_key(attributes, "trace_id")
          - set(span_id.string, attributes["span_id"]) where attributes["span_id"] != nil
          - delete_key(attributes, "span_id")
          - delete_key(attributes, "timestamp")
          - delete_key(attributes, "severity")
          # - set(body, Concat([attributes["method"], " ", attributes["path"], " → ", attributes["status"]], "")) where attributes["method"] != nil and attributes["message"] == nil
          # - set(body, attributes["message"]) where attributes["message"] != nil
          # - delete_key(attributes, "message")

exporters:
  otlp_http/mackerel:
    endpoint: https://otlp-vaxila.mackerelio.com
    compression: gzip
    headers:
      Accept: "*/*"
      Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
    sending_queue:
      batch:
        flush_timeout: 200ms
        min_size: 8192
  otlp/mackerel:
    endpoint: otlp.mackerelio.com:4317
    headers:
      Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
  debug:
    # verbosity: detailed

connectors:
  spanmetrics:
    metrics_flush_interval: 15s
    histogram:
      exponential:
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code

service:
  telemetry:
    metrics:
      readers:
        - periodic:
            interval: 60000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otel-collector:4319
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource/namespace]
      exporters: [otlp_http/mackerel, spanmetrics]
    logs:
      receivers: [otlp, filelog/app, fluentforward]
      processors: [resource/namespace_with_servicename, transform/applog]
      exporters: [otlp_http/mackerel]
    metrics:
      receivers: [otlp, hostmetrics, spanmetrics, mysql]
      processors: [resource/namespace_with_servicename, batch/1m]
      exporters: [otlp/mackerel]
