receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319
  mysql:
    endpoint: db:3306
    username: root
    password: mysql
    tls:
      insecure: true
    collection_interval: 30s
    initial_delay: 30s
  host_metrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
  fluent_forward:
    endpoint: 0.0.0.0:8006
  file_log/app:
    include: ["/app/log/*.log"]
    start_at: end
    operators:
      - type: json_parser
        parse_to: body
        on_error: send
        timestamp:
          parse_from: body.timestamp
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        severity:
          parse_from: body.severity

processors:
  resource/namespace:
    attributes:
      - key: service.namespace
        value: apm-demo
        action: upsert
  resource/namespace_with_servicename:
    attributes:
      - key: service.name
        value: sample-app
        action: insert
      - key: service.namespace
        value: apm-demo
        action: upsert
  transform/log_common:
    log_statements:
      - context: log
        statements:
          - set(trace_id.string, attributes["trace_id"]) where attributes["trace_id"] != nil
          - set(trace_id.string, body["trace_id"]) where IsMap(body) and body["trace_id"] != nil
          - delete_key(body, "trace_id") where IsMap(body)
          - set(span_id.string, attributes["span_id"]) where attributes["span_id"] != nil
          - set(span_id.string, body["span_id"]) where IsMap(body) and body["span_id"] != nil
          - delete_key(body, "span_id") where IsMap(body)
          - delete_key(attributes, "severity")
          - set(body["email"], SHA256(body["email"])) where IsMap(body)
          - set(body["phone"], "***") where IsMap(body)
          - delete_key(body, "token") where IsMap(body)
  transform/fluent_forward:
    error_mode: silent
    log_statements:
      - context: log
        statements:
          - set(body, ParseJSON(body)) where IsString(body)
          - set(severity_text, body["severity"]) where body["severity"] != nil
          - set(severity_number, SEVERITY_NUMBER_TRACE) where body["severity"] == "TRACE"
          - set(severity_number, SEVERITY_NUMBER_DEBUG) where body["severity"] == "DEBUG"
          - set(severity_number, SEVERITY_NUMBER_INFO) where body["severity"] == "INFO"
          - set(severity_number, SEVERITY_NUMBER_WARN) where body["severity"] == "WARN" or body["severity"] == "WARNING"
          - set(severity_number, SEVERITY_NUMBER_ERROR) where body["severity"] == "ERROR"
          - set(severity_number, SEVERITY_NUMBER_FATAL) where body["severity"] == "FATAL"

exporters:
  mackerel_otlp:
  # otlp_http/mackerel:
  #   endpoint: https://otlp-vaxila.mackerelio.com
  #   compression: gzip
  #   headers:
  #     Accept: "*/*"
  #     Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
  #   sending_queue:
  #     batch:
  #       flush_timeout: 200ms
  #       min_size: 3500000
  # otlp/mackerel:
  #   endpoint: otlp.mackerelio.com:4317
  #   headers:
  #     Mackerel-Api-Key: ${env:MACKEREL_APIKEY}
  #   sending_queue:
  #     batch:
  #       flush_timeout: 200ms
  #       min_size: 3500000
  debug:
    verbosity: detailed

connectors:
  span_metrics:
    metrics_flush_interval: 15s
    histogram:
      exponential:
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code

service:
  telemetry:
    metrics:
      readers:
        - periodic:
            interval: 60000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://otel-collector:4319
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource/namespace]
      exporters: [mackerel_otlp, span_metrics]
    logs:
      receivers: [otlp, file_log/app]
      processors: [resource/namespace_with_servicename, transform/log_common]
      exporters: [mackerel_otlp]
    logs/fluentforward:
      receivers: [fluent_forward]
      processors: [resource/namespace_with_servicename, transform/fluent_forward, transform/log_common]
      exporters: [mackerel_otlp]
    metrics:
      receivers: [otlp, host_metrics, span_metrics, mysql]
      processors: [resource/namespace_with_servicename]
      exporters: [mackerel_otlp]
