source "https://rubygems.org"

gem "sinatra"
gem "puma"
gem "rackup"

gem "opentelemetry-sdk", "~> 1.6"
gem "opentelemetry-instrumentation-sinatra"
gem "opentelemetry-instrumentation-net_http"
gem "opentelemetry-instrumentation-rack"
gem "opentelemetry-exporter-otlp", "~> 0.29.1"

gem "opentelemetry-logs-sdk", "~> 0.6.0"
gem "opentelemetry-exporter-otlp-logs", "~> 0.5.1"
